# helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
# helm repo list
# helm install my-sonarqube sonarqube/sonarqube --namespace sonarqube --create-namespace --values sonarqube-values.yaml --version 10.5.1
# kubectl get statefulset,pods,services --namespace sonarqube
# kubectl port-forward svc/my-sonarqube-sonarqube 31111:31111 --namespace sonarqube

service:
  type: NodePort
  nodePort: 31111

postgresql:
  persistence: 
    enabled: true

plugins:
  install:
   - 'https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v10.3/sonar-l10n-ru-plugin-10.3.jar'
   - 'https://github.com/jborgers/sonar-pmd/releases/download/3.5.1/sonar-pmd-plugin-3.5.1.jar'
   - 'https://github.com/checkstyle/sonar-checkstyle/releases/download/10.17.0/checkstyle-sonar-plugin-10.17.0.jar'