crds:
  keep: false

configs:
  secret:
    argocdServerAdminPassword: "qwertyqwerty" # real password is here
  repositories:
    - url: ${repoURL}
      name: root
      type: git

server:
  service:
    type: LoadBalancer
  config:
    resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs        