#----------------------------------------------------------------
# Fixing issue with Stuck Processing for Ingress resource
server:
  service:
    type: LoadBalancer
  config:
    resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs        